### ISSUE TITLE
ReadMail handling of MultiPart message type

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.mail#3]
In the ReadMail operator, we handle multi-part messages.  However, we seem to only concatenate the content together, making it hard for downstream operators to distinguish the different parts.

Perhaps we should emit an array of "content" with mime type attached, to mirror how emails are structured.

**Comment by joergboe** [comment]
In v2.0 the ReadMail operator provides a list of content and a list of content types.
